### PR TITLE
Using pipx to handle error: externally-managed-environment

### PR DESCRIPTION
**Pull request by rafaeldelucena**
From the [failed run](https://github.com/parkouss/funq/actions/runs/10241527944/job/28329932945?pr=82#step:3:117)

### CODE REVIEW

**Comment by rafaeldelucena** [comment]
@ubruhin I got this error with the CI for the PR https://github.com/parkouss/funq/pull/82

**Comment by ubruhin** [comment]
Thanks, I didn't notice it since there was no CI run for a long time.
I don't know why it still fails with pipx, but I've now tried the way I go normally and this works fine: #11

**Comment by ubruhin** [comment]
@rafaeldelucena Btw, something we should change in near future is to get rid of nosetest. It is not maintained anymore and doesn't run with recent Python versions, thus only one CI job is still executing the tests. My suggestion would be to remove the testing adapter completely from Funq, making it just a Python library so it can be used with *any* testing framework (for LibrePCB, we use it already with pytest). And of course the tests in this repo need to be converted to pytest or so. But unfortunately at the moment I don't have much time for that :-/

**Comment by rafaeldelucena** [comment]
> @rafaeldelucena Btw, something we should change in near future is to get rid of nosetest. It is not maintained anymore and doesn't run with recent Python versions, thus only one CI job is still executing the tests. My suggestion would be to remove the testing adapter completely from Funq, making it just a Python library so it can be used with _any_ testing framework (for LibrePCB, we use it already with pytest). And of course the tests in this repo need to be converted to pytest or so. But unfortunately at the moment I don't have much time for that :-/

I'm 100% on dropping nosetest in the flavor of pytest, I have a WIP branch with that somewhere, but didn't advance because we had no more CI running the tests, there are many good things to come, just need to run the tests again

**Comment by rafaeldelucena** [comment]
@ubruhin I'm closing this in favor of your fix in #11

**Comment by rafaeldelucena** [comment]
Not required anymore since #11

**Pull request closed without merging**
